name:                example-haskell-with-bazel
version:             0.1.0
homepage:            https://github.com/matsubara0507/example-haskell-with-bazel#readme
license:             MIT
author:              MATSUBARA Nobutada
maintainer:          nobutada0507@gmail.com
copyright:           2021 MATSUBARA Nobutada
category:            Web
description:         Please see the README on GitHub at <https://github.com/matsubara0507/example-haskell-with-bazel#readme>

extra-source-files:
- README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- GHC2021

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  salary-graph:
    main: Main.hs
    source-dirs: app
    dependencies:
    - example-haskell-with-bazel
