name: Example
on:
  pull_request: null
  push:
    branches:
    - main
jobs:
  ubuntu:
    name: Run Example (Ubuntu)
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ghc: ["9.2.1", "9.0.1", "8.10.7"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: run bazel example
      run: bazel run //:example-bin
      working-directory: ${{ matrix.ghc }}

  mac:
    name: Run Example (macOS)
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        ghc: ["9.2.1", "9.0.1", "8.10.7"]
    env:
      BAZEL_USE_CPP_ONLY_TOOLCHAIN: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: run bazel example
      run: bazel run //:example-bin
      working-directory: ${{ matrix.ghc }}

  windows:
    name: Run Example (Windows)
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        ghc: ["9.2.1", "9.0.1", "8.10.7"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: run bazel example
      run: bazel run --crosstool_top=@rules_haskell_ghc_windows_amd64//:cc_toolchain //:example-bin
      working-directory: ${{ matrix.ghc }}
